### ISSUE TITLE
es6-Promise should be es6-promise

### ISSUE THREAD

**Issue by aduros** [mozilla/node-firefox#28]
Almost all of the node-firefox modules have lines like this:

```js
var Promise = require('es6-Promise').Promise;
```

This fails on case-sensitive filesystems (Linux). The correct case is es6-promise.

After I made all the replacements, things seem to work surprisingly well on Linux! You might be able to update your support matrix after this change. ;)

(Example: https://github.com/mozilla/node-firefox-find-app/blob/master/index.js#L5)

**Comment by tofumatt** [comment]
Ah, thanks you! I recall this was caught someplace else but I guess not in
every module. Thanks!

-tofumatt

**Comment by lmorchard** [comment]
This should be fixed. I'm going to try doing some full runs of the module stack on Linux later today / tomorrow, so that will expose any more we've missed.

**Comment by aduros** [comment]
Thanks for the quick fixes!

It looks like launch-app and uninstall-app still need updating.

**Comment by lmorchard** [comment]
Doh, premature close then :) Threw in a couple of PRs for those two...

https://github.com/mozilla/node-firefox-launch-app/pull/4
https://github.com/mozilla/node-firefox-uninstall-app/pull/2

**Comment by tofumatt** [comment]
Merged, so once these are released on npm we should close

**Comment by tofumatt** [comment]
Just pushed updates to git and npm for all the modules!
