### ISSUE TITLE
Ability to start Firefox with remote debugging enabled

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox#4]
Currently to enable remote debugging you have to open the developer console and type `listen {port_number}`

This makes it impossible to run functional tests as we cannot launch Firefox and have it run on an specific port.

The solution would be to be able to:
```bash
firefox --remote-debugging-port=6000
```

there was some work going on this already: https://bugzilla.mozilla.org/show_bug.cgi?id=942756

**Comment by jryans** [comment]
It's sad that bug 942756 never landed, but it's a large patch set that I feel like is unlikely to revive.

I filed [another bug][1] to do only what's required here.

[1]: https://bugzil.la/1119894

**Comment by jryans** [comment]
The new bug landed "--start-debugger-server" in Firefox 37.
