### ISSUE TITLE
FireFox Focus border Issue

### ISSUE THREAD

**Issue by SandeepVerma10** [mozilla/node-firefox#45]
FireFox: when we navigate using tab, for some control left dotted border persists even if the focus is moved to next elements.
![firefox-focus-issue](https://user-images.githubusercontent.com/34231313/41540977-f9a6cd56-732e-11e8-94d0-afe24e89ce5d.png)

**Comment by tofumatt** [comment]
Sorry but this isn't the right place to report bugs with Firefox itself; this is an old project used to interact with Firefox(OS) via node.

Please report bugs in Firefox at https://bugzilla.mozilla.org with as much info as possible–steps to reproduce, your OS/browser version, etc. The screenshot is definitely helpful 😄
